export default {
    EMAIL_REPLACEABLE: /[^a-zA-Z0-9@._-À-ÖØ-öø-ÿ´~`^¨]+/g,
    EMAIL: /^[\w!#$%&'*+/=?^_`{|}~-]+(?:\.[\w!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$/,
    PHONE: /^\d{11}$/,
    CEP: /^\d{8}$/,
    CPF: /^\d{11}$/,
    TEXT_REPLACEABLE: /[^a-zA-ZÀ-ÖØ-öø-ÿ´~`^¨]/g,
    TEXT: /^[a-zA-ZÀ-ÖØ-öø-ÿ]+$/,
    NUMBER_REPLACEABLE: /[^0-9]/g,
    NUMBER: /^[0-9]+$/,
    NUMBER_SPACE: /^[0-9\s]+$/,
    TEXT_SPACE_REPLACEABLE: /[^a-zA-Z\sÀ-ÖØ-öø-ÿ´~`^¨]/g,
    TEXT_SPACE: /^[a-zA-Z\sÀ-ÖØ-öø-ÿ]+$/,
    TEXT_NUMBER: /^[a-zA-Z0-9]+$/,
    TEXT_NUMBER: /^[a-zA-Z0-9]+$/,
    TEXT_NUMBER_SPACE: /^[a-zA-Z0-9\sÀ-ÖØ-öø-ÿ]+$/,
    BETWEEN_8_AND_24: /^.{8,24}$/,
}